### ISSUE TITLE
Response size rows fixed to 50.000

### ISSUE THREAD

**Issue by marcelschliesser** [benpowis/search-console-bq#11]
Hey @benpowis ,
over the last 3 years i downloaded the data for a GSC Property and never get more than 50.000 rows back.

See also https://support.google.com/webmasters/thread/54859691/google-search-console-api-rows-capped-to-50000?hl=en

I think it is not necessary to loop until 100.000 Rows.

**Comment by benpowis** [comment]
Hey @marcelschliesser 

Yes, I would agree with you reading that link, I added this into the code to allow for future growth, but checking my own code I now see that I never pull more than 50k rows per property.
