### ISSUE TITLE
API library change

### ISSUE THREAD

**Issue by whatevaman** [benpowis/search-console-bq#12]
https://developers.google.com/search/blog/2020/12/search-console-api-updates#discovery-doc-migration

I suppose, the following is what needs to be changed at least? Tested with the updated service names, and woring. Is there anything else that needs to be updated, after support for the current library drops? BW

```
service = build(
    'searchconsole',
    'v1',
    credentials=credentials
)
```

**Comment by benpowis** [comment]
hey @whatevaman !

Looks good to me! Would you like to raise this as a pull request to forever log your contribution to this code? :)

 Ben

**Comment by whatevaman** [comment]
I am delight, pull request sent. :)
