### ISSUE TITLE
Service Account File

### ISSUE THREAD

**Issue by featdd** [benpowis/search-console-bq#2]
Hi @benpowis,

I created a service account file but the api won't grant me access to the property.
I followed the instructions on the google cloud documentation but can there be something else to consider?

This is the error message I got:
`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/webmasters/v3/sites/XXXPropertyXXX/searchAnalytics/query?alt=json returned "User does not have sufficient permission for site 'XXXPropertyXXX'. See also: https://support.google.com/webmasters/answer/2451999.">`

The used account definietely has access to the search console as a delegated owner.

Greetings
Daniel

**Comment by benpowis** [comment]
Hi @featdd 

It sounds like you have done everything correctly - you could double check you have authed the correct email address by opening up the .json key file and ensuring that the email address within is the one that has permissions on the GSC property.

I have my accounts granted 'Full' permissions, try this with yours too, if not already?

Best,
Ben

**Comment by featdd** [comment]
Hi @benpowis,

I just found solved the issue with the help of a collegue.

The E-Mail Adress for the service account had to be added to the search console in order to grant access to it.

But thanks for your quick response and for your script.

Greetings
Daniel
