### ISSUE TITLE
User Permissions problem despite following all steps instructed 

### ISSUE THREAD

**Issue by Prathamesh-Hoshing** [benpowis/search-console-bq#5]
Hi Ben,

I would like to first thank you for the work put into this. I am trying to test your code for streaming Search Console data into BigQuery.

I have so far followed all the steps:
- Activated 'Google Search Console API'
- Create a service account, provide it 'Full' access on Search Console and 'Data Owner' permission on Google Cloud Platform
- Added parameters

I face a permission problem at this snippet of code

# Make the request to grab the data
response = service.searchanalytics().query(siteUrl=site_url, body=request).execute()
# Go down one level in the response object
res = response['rows']
# Create a DataFrame of the results
df = pd.DataFrame.from_dict(res)

I get the following error: <HttpError 403 when requesting https://www.googleapis.com/webmasters/v3/sites/https%3A%2F%2Fwww.xxx.com/searchAnalytics/query?alt=json returned "User does not have sufficient permission for site 'https://www.xxx.com'. 

Changed the real website to xxx.com above.

What's going wrong?

Thanks in advance for your help.

**Comment by benpowis** [comment]
Hi Prathamesh,

Thanks for reaching out, can you confirm you have granted sufficient permissions for your service account on your search console user panel?

Ben

**Comment by parichayawalia** [comment]
hi @Prathamesh-Hoshing , @benpowis 
i am facing the same issue. 
could you help me understand how this is to be resolved?

**Comment by benpowis** [comment]
Hi @Prathamesh-Hoshing 
This is usually caused by the service account user not having been correctly authorised in Google Search Console. Could you review these setup steps again? If you can share details on the steps you have a taken I am happy to review them.
Ben
