### ISSUE TITLE
Property destination is unknown for <class 'google.cloud.bigquery.job.load.LoadJobConfig'>.

### ISSUE THREAD

**Issue by ryanhansen93** [benpowis/search-console-bq#7]
Hi, I'm getting the following AttributeError: "Property destination is unknown for <class 'google.cloud.bigquery.job.load.LoadJobConfig'>." Any advice? Thank you!

**Comment by benpowis** [comment]
Hey Ryan, apologies for the delay in getting back to you here - were you able to resolve this issue?

**Comment by ryanhansen93** [comment]
Hey Ben, I took another route and got it to work. Thanks for the reply!
